### ISSUE TITLE
Auto fishing sometimes causes game to crash

### ISSUE THREAD

**Issue by Alge** [Zergatul/cheatutils#114]
Sometimes the game crashes when using the auto fisher

<details>

<summary>Crash report</summary>
```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2024-12-16 10:17:03
Description: Accessing LegacyRandomSource from multiple threads

java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at knot//net.minecraft.class_5798.method_33564(class_5798.java:84)
	at knot//net.minecraft.class_5820.method_43156(class_5820.java:49)
	at knot//net.minecraft.class_6566.method_43048(class_6566.java:27)
	at knot//net.minecraft.class_638.method_2943(class_638.java:389)
	at knot//net.minecraft.class_638.method_2941(class_638.java:368)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1929)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1313)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_5798.method_33564(class_5798.java:84)
	at knot//net.minecraft.class_5820.method_43156(class_5820.java:49)
	at knot//net.minecraft.class_6566.method_43048(class_6566.java:27)
	at knot//net.minecraft.class_638.method_2943(class_638.java:389)
	at knot//net.minecraft.class_638.method_2941(class_638.java:368)

-- Thread dumps --
Details:
	Thread dumps: Render thread: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:2450)
	at knot//net.minecraft.class_5798.method_39936(class_5798.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at knot//net.minecraft.class_5798.method_33564(class_5798.java:82)
	at knot//net.minecraft.class_5820.method_43156(class_5820.java:49)
	at knot//net.minecraft.class_6566.method_43048(class_6566.java:27)
	at knot//net.minecraft.class_638.method_2943(class_638.java:389)
	at knot//net.minecraft.class_638.method_2941(class_638.java:368)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1929)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1313)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Stacktrace:
	at knot//net.minecraft.class_5798.method_33564(class_5798.java:84)
	at knot//net.minecraft.class_5820.method_43156(class_5820.java:49)
	at knot//net.minecraft.class_6566.method_43048(class_6566.java:27)
	at knot//net.minecraft.class_638.method_2943(class_638.java:389)
	at knot//net.minecraft.class_638.method_2941(class_638.java:368)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1929)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1313)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 6075.873s
	Wall uptime: 6069.653s
	High-res time: 6067.066s
	Client ticks: 110591 ticks / 5529.550s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:954)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['MyMinecraftUsername'/117845, l='ClientLevel', x=-1143.85, y=63.00, z=253.58]]
	Chunk stats: 5041, 2516
	Level dimension: minecraft:overworld
	Level spawn location: World: (-1216,67,141), Section: (at 0,3,13 in -76,4,8; chunk contains blocks -1216,-64,128 to -1201,319,143), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,-64,0 to -1025,319,511)
	Level time: 11573442 game time, 12295122 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
	Tracked entity count: 254

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, balm-fabric, cheatutils, chunksfadein, cloth-config, craftingtweaks, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, freecam, lithium, numeralping, sodium, xaerominimap, xaeroworldmap, yet_another_config_lib_v3

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Linux (amd64) version 6.8.0-50-generic
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 884515160 bytes (843 MiB) / 2503999488 bytes (2388 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700X 8-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.66
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Navi 23 [Radeon RX 6600/6600 XT/6600M]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MiB): 258.00
	Graphics card #0 deviceId: 0x73ff
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 24191.05
	Virtual memory used (MiB): 11593.57
	Swap memory total (MiB): 8192.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 1465528.13, total: 3262293.75
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 1465528.13, total: 3262293.75
	Space in storage for io.netty.native.workdir (MiB): available: 1465528.13, total: 3262293.75
	Space in storage for java.io.tmpdir (MiB): available: 1465528.13, total: 3262293.75
	Space in storage for workdir (MiB): available: 1465528.13, total: 3262293.75
	JVM Flags: 3 total; -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		balm-fabric: Balm 21.3.3
			kuma_api: KumaAPI 21.3.1-SNAPSHOT
		cheatutils: CheatUtils 3.3.2
		chunksfadein: Chunks Fade In 2.0.3-1.21.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		craftingtweaks: Crafting Tweaks 21.3.3
		fabric-api: Fabric API 0.110.0+1.21.3
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.81+fd37071f40
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.6+fd37071f40
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+fd37071f40
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.4+fd37071f40
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.24+fd37071f40
			fabric-command-api-v1: Fabric Command API (v1) 1.2.58+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.37+c9d82ab240
			fabric-commands-v0: Fabric Commands (v0) 0.2.75+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.8+fd37071f40
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.3+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.3+84ebbb0e40
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+fd37071f40
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+dbad41f140
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.18+fd37071f40
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+fd37071f40
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.8+825023f840
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.12+c2c3ac4740
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+fd37071f40
			fabric-item-api-v1: Fabric Item API (v1) 11.1.7+fd37071f40
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.17+fd37071f40
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+fd37071f40
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b340
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.1+6da5ef6940
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.26+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.14+fd37071f40
			fabric-message-api-v1: Fabric Message API (v1) 6.0.21+fd37071f40
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.9+fd37071f40
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.5+fd37071f40
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.9+fd37071f40
			fabric-particles-v1: Fabric Particles (v1) 4.0.10+fd37071f40
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.4+fd37071f40
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.3.0+2758bfbf40
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.5+fd37071f40
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.84+df3654b340
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.8+6922831640
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+fd37071f40
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.34+fd37071f40
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.101+fd37071f40
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+fd37071f40
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.3+fd37071f40
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+54a41b1c40
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		freecam: Freecam 1.3.1+mc1.21.3
			cloth-config: Cloth Config v16 16.0.141
				cloth-basic-math: cloth-basic-math 0.6.1
		java: OpenJDK 64-Bit Server VM 21
		lithium: Lithium 0.14.3+mc1.21.3
		minecraft: Minecraft 1.21.3
		mousetweaks: Mouse Tweaks 2.27
		numeralping: Numeral Ping 1.2.5
		sodium: Sodium 0.6.3+mc1.21.3
			fabric-api-base: Fabric API Base 0.4.50+119c825640
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+fd37071f40
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.5+fd37071f40
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.15+fd37071f40
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.6+fd37071f40
		xaerominimap: Xaero's Minimap 24.6.2
		xaeroworldmap: Xaero's World Map 1.39.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.2+1.21.2-fabric
			com_twelvemonkeys_common_common-image: common-image 3.12.0
			com_twelvemonkeys_common_common-io: common-io 3.12.0
			com_twelvemonkeys_common_common-lang: common-lang 3.12.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: fabric-loader-0.16.9-1.21.3
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon RX 6600 (radeonsi, navi23, LLVM 17.0.6, DRM 3.57, 6.8.0-50-generic) GL version 4.6 (Core Profile) Mesa 24.0.9-0ubuntu0.2, AMD
	Window size: 1498x1659
	GFLW Platform: x11
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 32/32 chunks
	Resource Packs: vanilla, fabric, balm-fabric (incompatible), cheatutils, chunksfadein, cloth-config, craftingtweaks (incompatible), fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, freecam, lithium, numeralping, sodium, xaerominimap (incompatible), xaeroworldmap (incompatible), yet_another_config_lib_v3 (incompatible)
	Current Language: en_us
	Locale: en_US
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: 16x AMD Ryzen 7 5700X 8-Core Processor
```

</details>

**Comment by Zergatul** [comment]
i noticed this too while working on recast for 1.21.4
