### ISSUE TITLE
cheatutils-3.3.3-fabric 1.21.4 crashes, says theres no fabric

### ISSUE THREAD

**Issue by augis-hub** [Zergatul/cheatutils#116]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, any version.
More details:
	 - Mod 'CheatUtils' (cheatutils) 3.3.3 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
![image](https://github.com/user-attachments/assets/8fe49b1f-6334-450e-8053-2627e79ae4db)

![image](https://github.com/user-attachments/assets/1d4ac7df-3b6a-4705-847b-39ffb23404d2)

**Comment by Zergatul** [comment]
I got the same error when trying to start without fabric API. Added fabric API and error went away. But you seem to have fabric API.

**Comment by augis-hub** [comment]
> I got the same error when trying to start without fabric API. Added fabric API and error went away. But you seem to have fabric API.

so what should i do then??

**Comment by Zergatul** [comment]
I don't know. Something must be wrong on your side. 500 downloads and only you have this issue. Maybe it is really some sort of weird conflict with another mod? But I never saw this before. Try to start the game with only cheatutils and fabric API. If it works - add another mods one by one
