### ISSUE TITLE
crashes in 1.19.3

### ISSUE THREAD

**Issue by end-user** [Zergatul/cheatutils#12]
Cannot load with 1.19.3 (fabric):

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'cheatutils'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoSuchFieldError: field_11146
	at com.zergatul.cheatutils.wrappers.ModApiWrapper.<clinit>(ModApiWrapper.java:13)
	at com.zergatul.cheatutils.ModMain.onInitializeClient(ModMain.java:21)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 16 more
```

**Comment by Zergatul** [comment]
I see Mojang made a lot of refactoring of geometry related code, matrices, vectors and similar stuff. This will take some time to fix.

**Comment by Zergatul** [comment]
Added 1.19.3 version

**Comment by end-user** [comment]
That was fast!  Looks like the fabric version only offers ESP and Freecam, and the ESP doesn't appear to be working.  I was actually specifically looking for kill aura in fabric - is that going to be available?  FWIW, there's a separate freecam mod, so that feature is a little redundant other than the convenience of having it all in one place.

**Comment by Zergatul** [comment]
Fabric version has Kill Aura (under Hacks column). ESP should work. There is rare bug (it happens more often for some users) with Blocks ESP. But Entity ESP is stable. You can use other FreeCam mod, but it is better to use embedded freecam, since some modules have integration with native freecam, and there interactions will not work with another freecams (for example Exploration Mini Map module)

**Comment by end-user** [comment]
Ok, I see it now.  Is there any way to be more granular on what can be targeted?  It appears to ignore passive mobs.

**Comment by Zergatul** [comment]
I added this to forge version about week ago. I can add this to fabric, but I have a lot of other requests, so it will not be very soon

**Comment by end-user** [comment]
ok, cool.  Yeah, it would be super helpful to just be able to specify a list of things to target.  Specifically, I'm looking to be able to hit bats (which doesn't seem to be a target of "flying mobs").

**Comment by Zergatul** [comment]
Moved forge Kill Aura changes to fabric version. Check 0.11.0 fabric. It may take some time before curseforge approve file.

**Comment by end-user** [comment]
Works in 1.19.3
