### ISSUE TITLE
Current Incompatibility with Fabric Lithium.

### ISSUE THREAD

**Issue by Oxeus** [Zergatul/cheatutils#85]
Registry minecraft:banner_pattern not found
**********
	at net.minecraft.class_7225$class_7874.method_46763(class_7225.java:107)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.minecraft.class_7225$class_7874.method_46762(class_7225.java:107)
	at net.minecraft.class_1937.handler$cdg000$lithium$initCachedOminousBanner(class_1937.java:3068)
	at net.minecraft.class_1937.<init>(class_1937.java:166)
	at com.zergatul.cheatutils.utils.EntityUtils$FakeLevel.<init>(EntityUtils.java:258)
	at com.zergatul.cheatutils.utils.EntityUtils.loadEntityClasses(EntityUtils.java:125)
	at com.zergatul.cheatutils.utils.EntityUtils.getEntityClasses(EntityUtils.java:66)
	at com.zergatul.cheatutils.webui.EntityInfoApi.get(EntityInfoApi.java:15)
	at com.zergatul.cheatutils.webui.ApiHandler.processGet(ApiHandler.java:923)
	at com.zergatul.cheatutils.webui.ApiHandler.handle(ApiHandler.java:887)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:871)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:847)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:204)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:566)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:532)
	at java.base/java.lang.Thread.run(Thread.java:1583)

When trying to grab entities the game still runs but errors out with this reported from localhost:5005/api/entity-info.

**Comment by Zergatul** [comment]
What MC version are you using

**Comment by Oxeus** [comment]
1.20.6

**Comment by Oxeus** [comment]
The function runs fine if Fabric Lithium is removed.

**Comment by Zergatul** [comment]
This must be fixed in 2.15.0 version
